#!/usr/bin/env python3
"""Prepare the live-root source request used to freeze Design Boundary V6."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


EPOCH = "2026-08-28-plan-successor-design-boundary-v6-evidence-repair"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--source", required=True, type=Path)
    parser.add_argument("--output", required=True, type=Path)
    args = parser.parse_args()
    if args.output.exists() or args.output.is_symlink():
        raise ValueError("--output must be absent")

    request = json.loads(args.source.read_text(encoding="utf-8"))
    document = request["document"]
    document["observation_epoch"] = EPOCH

    replaced_script_rules = 0
    repaired_fixture_rule = False
    for rule in document["discovery_rules"]:
        globs = rule["include_globs"]
        if "scripts/**" in globs:
            rule["include_globs"] = [
                "scripts/*.py" if pattern == "scripts/**" else pattern
                for pattern in globs
            ]
            replaced_script_rules += 1
        if rule["rule_id"] == "rule:invoke-plan-quality":
            expected = "development/fixtures/define-intent-coverage/*.json"
            if expected not in rule["include_globs"]:
                raise ValueError(f"missing expected V5 fixture selector: {expected}")
            rule["include_globs"] = [
                pattern
                for pattern in rule["include_globs"]
                if pattern != expected
            ] + [
                "development/fixtures/define-intent-coverage/fixture-matrix.json",
                "development/fixtures/define-intent-coverage/incident-manifest.json",
            ]
            repaired_fixture_rule = True

    if replaced_script_rules != 4:
        raise ValueError(
            f"expected four broad scripts rules, found {replaced_script_rules}"
        )
    if not repaired_fixture_rule:
        raise ValueError("missing Invoke Plan quality rule")

    forbidden_fragments = ("__pycache__", ".pyc", ".pyo", ".pyd")
    for rule in document["discovery_rules"]:
        for pattern in rule["include_globs"]:
            if any(fragment in pattern for fragment in forbidden_fragments):
                raise ValueError(
                    f"generated bytecode selector is forbidden in V6: {pattern}"
                )

    args.output.write_text(
        json.dumps(request, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
